window.geoHierarchy = 
  { 'continents': [ { 'continent_name': 'North America',
                      'country_ids': ['11', '12', '13']
                    },
                    { 'continent_name': 'South America',
                      'country_ids': ['21', '22', '23', '24', '25', '26']
                    },
                    { 'continent_name': 'Europe',
                      'country_ids': ['31', '32', '33', '34', '35', '36', '37']
                    },
                    { 'continent_name': 'Africa',
                      'country_ids': ['41', '42', '43', '44', '45']
                    },
                    { 'continent_name': 'Asia',
                      'country_ids': ['51', '52', '53', '54', '55', '56']
                    },
                    { 'continent_name': 'Oceania',
                      'country_ids': ['61', '62', '63', '64']
                    }
                  ],
    'countries':  { '11': { 'country_name': 'Canada',
                            'city_ids': ['111', '112', '113', '114', '115']
                          },
                    '12': { 'country_name': 'Mexico',
                            'city_ids': ['121', '122', '123', '124', '125']
                          },
                    '13': { 'country_name': 'United States',
                            'city_ids': ['131', '132', '133', '134', '135']
                          },
                    '21': { 'country_name': 'Argentina',
                            'city_ids': ['211', '212', '213', '214', '215']
                          },
                    '22': { 'country_name': 'Brazil',
                            'city_ids': ['221', '222', '223', '224', '225']
                          },
                    '23': { 'country_name': 'Chile',
                            'city_ids': ['231', '232', '233', '234', '235']
                          },
                    '24': { 'country_name': 'Colombia',
                            'city_ids': ['241', '242', '243', '244', '245']
                          },
                    '25': { 'country_name': 'Peru',
                            'city_ids': ['251', '252', '253', '254', '255']
                          },
                    '26': { 'country_name': 'Venezuela',
                            'city_ids': ['261', '262', '263', '264', '265']
                          },
                    '31': { 'country_name': 'France',
                            'city_ids': ['311', '312', '313', '314', '315']
                          },
                    '32': { 'country_name': 'Germany',
                            'city_ids': ['321', '322', '323', '324', '325']
                          },
                    '33': { 'country_name': 'Greece',
                            'city_ids': ['331', '332', '333', '334', '335']
                          },
                    '34': { 'country_name': 'Italy',
                            'city_ids': ['341', '342', '343', '344', '345']
                          },
                    '35': { 'country_name': 'Netherlands',
                            'city_ids': ['351', '352', '353', '354', '355']
                          },
                    '36': { 'country_name': 'Spain',
                            'city_ids': ['361', '362', '363', '364', '365']
                          },
                    '37': { 'country_name': 'Sweden',
                            'city_ids': ['371', '372', '373', '374', '375']
                          },
                    '41': { 'country_name': 'Congo',
                            'city_ids': ['411', '412', '413', '414', '415']
                          },
                    '42': { 'country_name': 'Egypt',
                            'city_ids': ['421', '422', '423', '424', '425']
                          },
                    '43': { 'country_name': 'Ethiopia',
                            'city_ids': ['431', '432', '433', '434', '435']
                          },
                    '44': { 'country_name': 'Nigeria',
                            'city_ids': ['441', '442', '443', '444', '445']
                          },
                    '45': { 'country_name': 'South Africa',
                            'city_ids': ['451', '452', '453', '454', '455']
                          },
                    '51': { 'country_name': 'China',
                            'city_ids': ['511', '512', '513', '514', '515']
                          },
                    '52': { 'country_name': 'India',
                            'city_ids': ['521', '522', '523', '524', '525']
                          },
                    '53': { 'country_name': 'Japan',
                            'city_ids': ['531', '532', '533', '534', '535']
                          },
                    '54': { 'country_name': 'Malaysia',
                            'city_ids': ['541', '542', '543', '544', '545']
                          },
                    '55': { 'country_name': 'Mongolia',
                            'city_ids': ['551', '552', '553', '554', '555']
                          },
                    '56': { 'country_name': 'South Korea',
                            'city_ids': ['561', '562', '563', '564', '565']
                          },
                    '61': { 'country_name': 'Australia',
                            'city_ids': ['611', '612', '613', '614', '615']
                          },
                    '62': { 'country_name': 'Indonesia',
                            'city_ids': ['621', '622', '623', '624', '625']
                          },
                    '63': { 'country_name': 'New Zealand',
                            'city_ids': ['631', '632', '633', '634', '635']
                          },
                    '64': { 'country_name': 'Philippines',
                            'city_ids': ['641', '642', '643', '644', '645']
                          }
                  },
    'cities':     { '111': { 'city_name': 'Montreal',
                             'admin_division_name': 'Quebec',
                             'country_name': 'Canada',
                             'continent_name': 'North America',
                             'population': '3,268,513'
                           },
                    '112': { 'city_name': 'Toronto',
                             'admin_division_name': 'Ontario',
                             'country_name': 'Canada',
                             'continent_name': 'North America',
                             'population': '2,600,000'
                           },
                    '113': { 'city_name': 'Vancouver',
                             'admin_division_name': 'British Columbia',
                             'country_name': 'Canada',
                             'continent_name': 'North America',
                             'population': '1,837,969'
                           },
                    '114': { 'city_name': 'Calgary',
                             'admin_division_name': 'Alberta',
                             'country_name': 'Canada',
                             'continent_name': 'North America',
                             'population': '1,019,942'
                           },
                    '115': { 'city_name': 'Ottawa',
                             'admin_division_name': 'Ontario',
                             'country_name': 'Canada',
                             'continent_name': 'North America',
                             'population': '812,129'
                           },
                    '121': { 'city_name': 'Mexico City',
                             'admin_division_name': 'Mexico City',
                             'country_name': 'Mexico',
                             'continent_name': 'North America',
                             'population': '12,294,193'
                           },
                    '122': { 'city_name': 'Iztapalapa',
                             'admin_division_name': 'Mexico City',
                             'country_name': 'Mexico',
                             'continent_name': 'North America',
                             'population': '1,820,888'
                           },
                    '123': { 'city_name': 'Ecatepec de Morelos',
                             'admin_division_name': 'Mexico',
                             'country_name': 'Mexico',
                             'continent_name': 'North America',
                             'population': '1,806,226'
                           },
                    '124': { 'city_name': 'Guadalajara',
                             'admin_division_name': 'Jalisco',
                             'country_name': 'Mexico',
                             'continent_name': 'North America',
                             'population': '1,640,589'
                           },
                    '125': { 'city_name': 'Puebla',
                             'admin_division_name': 'Puebla',
                             'country_name': 'Mexico',
                             'continent_name': 'North America',
                             'population': '1,590,256'
                           },
                    '131': { 'city_name': 'New York',
                             'admin_division_name': 'New York',
                             'country_name': 'United States of America',
                             'continent_name': 'North America',
                             'population': '8,175,133'
                           },
                    '132': { 'city_name': 'Los Angeles',
                             'admin_division_name': 'California',
                             'country_name': 'United States of America',
                             'continent_name': 'North America',
                             'population': '3,792,621'
                           },
                    '133': { 'city_name': 'Chicago',
                             'admin_division_name': 'Illinois',
                             'country_name': 'United States of America',
                             'continent_name': 'North America',
                             'population': '2,695,598'
                           },
                    '134': { 'city_name': 'Brooklyn',
                             'admin_division_name': 'New York',
                             'country_name': 'United States of America',
                             'continent_name': 'North America',
                             'population': '2,300,664'
                           },
                    '135': { 'city_name': 'Borough of Queens',
                             'admin_division_name': 'New York',
                             'country_name': 'United States of America',
                             'continent_name': 'North America',
                             'population': '2,272,771'
                           },
                    '211': { 'city_name': 'Buenos Aires',
                             'admin_division_name': 'Buenos Aires',
                             'country_name': 'Argentina',
                             'continent_name': 'South America',
                             'population': '13,076,300'
                           },
                    '212': { 'city_name': 'Cordoba',
                             'admin_division_name': 'Cordoba',
                             'country_name': 'Argentina',
                             'continent_name': 'South America',
                             'population': '1,428,214'
                           },
                    '213': { 'city_name': 'Rosario',
                             'admin_division_name': 'Santa Fe',
                             'country_name': 'Argentina',
                             'continent_name': 'South America',
                             'population': '1,173,533'
                           },
                    '214': { 'city_name': 'Mendoza',
                             'admin_division_name': 'Mendoza',
                             'country_name': 'Argentina',
                             'continent_name': 'South America',
                             'population': '876,884'
                           },
                    '215': { 'city_name': 'San Miguel de Tucuman',
                             'admin_division_name': 'Tucuman',
                             'country_name': 'Argentina',
                             'continent_name': 'South America',
                             'population': '781,023'
                           },
                    '221': { 'city_name': 'Sao Paulo',
                             'admin_division_name': 'Sao Paulo',
                             'country_name': 'Brazil',
                             'continent_name': 'South America',
                             'population': '10,021,295'
                           },
                    '222': { 'city_name': 'Rio de Janeiro',
                             'admin_division_name': 'Rio de Janeiro',
                             'country_name': 'Brazil',
                             'continent_name': 'South America',
                             'population': '6,023,699'
                           },
                    '223': { 'city_name': 'Salvador',
                             'admin_division_name': 'Bahia',
                             'country_name': 'Brazil',
                             'continent_name': 'South America',
                             'population': '2,711,840'
                           },
                    '224': { 'city_name': 'Fortaleza',
                             'admin_division_name': 'Ceara',
                             'country_name': 'Brazil',
                             'continent_name': 'South America',
                             'population': '2,400,000'
                           },
                    '225': { 'city_name': 'Belo Horizonte',
                             'admin_division_name': 'Minas Gerais',
                             'country_name': 'Brazil',
                             'continent_name': 'South America',
                             'population': '2,373,224'
                           },
                    '231': { 'city_name': 'Santiago',
                             'admin_division_name': 'Santiago Metropolitan',
                             'country_name': 'Chile',
                             'continent_name': 'South America',
                             'population': '4,837,295'
                           },
                    '232': { 'city_name': 'Puente Alto',
                             'admin_division_name': 'Santiago Metropolitan',
                             'country_name': 'Chile',
                             'continent_name': 'South America',
                             'population': '510,417'
                           },
                    '233': { 'city_name': 'Antofagasta',
                             'admin_division_name': 'Antofagasta',
                             'country_name': 'Chile',
                             'continent_name': 'South America',
                             'population': '309,832'
                           },
                    '234': { 'city_name': 'Vina del Mar',
                             'admin_division_name': 'Valparaiso',
                             'country_name': 'Chile',
                             'continent_name': 'South America',
                             'population': '294,551'
                           },
                    '235': { 'city_name': 'Valparaiso',
                             'admin_division_name': 'Valparaiso',
                             'country_name': 'Chile',
                             'continent_name': 'South America',
                             'population': '282,448'
                           },
                    '241': { 'city_name': 'Bogota',
                             'admin_division_name': 'Bogota',
                             'country_name': 'Colombia',
                             'continent_name': 'South America',
                             'population': '7,674,366'
                           },
                    '242': { 'city_name': 'Santiago de Cali',
                             'admin_division_name': 'Valle del Cauca',
                             'country_name': 'Colombia',
                             'continent_name': 'South America',
                             'population': '2,392,877'
                           },
                    '243': { 'city_name': 'Medellin',
                             'admin_division_name': 'Antioquia',
                             'country_name': 'Colombia',
                             'continent_name': 'South America',
                             'population': '1,999,979'
                           },
                    '244': { 'city_name': 'Barranquilla',
                             'admin_division_name': 'Atlantico',
                             'country_name': 'Colombia',
                             'continent_name': 'South America',
                             'population': '1,380,425'
                           },
                    '245': { 'city_name': 'Cartagena',
                             'admin_division_name': 'Bolivar',
                             'country_name': 'Colombia',
                             'continent_name': 'South America',
                             'population': '952,024'
                           },
                    '251': { 'city_name': 'Lima',
                             'admin_division_name': 'Lima',
                             'country_name': 'Peru',
                             'continent_name': 'South America',
                             'population': '7,737,002'
                           },
                    '252': { 'city_name': 'Arequipa',
                             'admin_division_name': 'Arequipa',
                             'country_name': 'Peru',
                             'continent_name': 'South America',
                             'population': '841,130'
                           },
                    '253': { 'city_name': 'Callao',
                             'admin_division_name': 'Callao',
                             'country_name': 'Peru',
                             'continent_name': 'South America',
                             'population': '813,264'
                           },
                    '254': { 'city_name': 'Trujillo',
                             'admin_division_name': 'La Libertad',
                             'country_name': 'Peru',
                             'continent_name': 'South America',
                             'population': '747,450'
                           },
                    '255': { 'city_name': 'Chiclayo',
                             'admin_division_name': 'Lambayeque',
                             'country_name': 'Peru',
                             'continent_name': 'South America',
                             'population': '577,375'
                           },
                    '261': { 'city_name': 'Caracas',
                             'admin_division_name': 'Caracas',
                             'country_name': 'Venezuela',
                             'continent_name': 'South America',
                             'population': '3,000,000'
                           },
                    '262': { 'city_name': 'Maracaibo',
                             'admin_division_name': 'Zulia',
                             'country_name': 'Venezuela',
                             'continent_name': 'South America',
                             'population': '2,225,000'
                           },
                    '263': { 'city_name': 'Maracay',
                             'admin_division_name': 'Aragua',
                             'country_name': 'Venezuela',
                             'continent_name': 'South America',
                             'population': '1,754,256'
                           },
                    '264': { 'city_name': 'Valencia',
                             'admin_division_name': 'Carabobo',
                             'country_name': 'Venezuela',
                             'continent_name': 'South America',
                             'population': '1,385,083'
                           },
                    '265': { 'city_name': 'Barquisimeto',
                             'admin_division_name': 'Lara',
                             'country_name': 'Venezuela',
                             'continent_name': 'South America',
                             'population': '809,490'
                           },
                    '311': { 'city_name': 'Paris',
                             'admin_division_name': 'Ile-de-France',
                             'country_name': 'France',
                             'continent_name': 'Europe',
                             'population': '2,138,551'
                           },
                    '312': { 'city_name': 'Marseille',
                             'admin_division_name': 'Provence-Alpes-Cote dAzur',
                             'country_name': 'France',
                             'continent_name': 'Europe',
                             'population': '794,811'
                           },
                    '313': { 'city_name': 'Lyon',
                             'admin_division_name': 'Rhone-Alpes',
                             'country_name': 'France',
                             'continent_name': 'Europe',
                             'population': '472,317'
                           },
                    '314': { 'city_name': 'Toulouse',
                             'admin_division_name': 'Midi-Pyrenees',
                             'country_name': 'France',
                             'continent_name': 'Europe',
                             'population': '433,055'
                           },
                    '315': { 'city_name': 'Nice',
                             'admin_division_name': 'Provence-Alpes-Cote dAzur',
                             'country_name': 'France',
                             'continent_name': 'Europe',
                             'population': '338,620'
                           },
                    '321': { 'city_name': 'Berlin',
                             'admin_division_name': 'Berlin',
                             'country_name': 'Germany',
                             'continent_name': 'Europe',
                             'population': '3,426,354'
                           },
                    '322': { 'city_name': 'Hamburg',
                             'admin_division_name': 'Hamburg',
                             'country_name': 'Germany',
                             'continent_name': 'Europe',
                             'population': '1,739,117'
                           },
                    '323': { 'city_name': 'Munich',
                             'admin_division_name': 'Bavaria',
                             'country_name': 'Germany',
                             'continent_name': 'Europe',
                             'population': '1,260,391'
                           },
                    '324': { 'city_name': 'Cologne',
                             'admin_division_name': 'North Rhine-Westphalia',
                             'country_name': 'Germany',
                             'continent_name': 'Europe',
                             'population': '963,395'
                           },
                    '325': { 'city_name': 'Frankfurt am Main',
                             'admin_division_name': 'Hesse',
                             'country_name': 'Germany',
                             'continent_name': 'Europe',
                             'population': '650,000'
                           },
                    '331': { 'city_name': 'Athens',
                             'admin_division_name': 'Attica',
                             'country_name': 'Greece',
                             'continent_name': 'Europe',
                             'population': '664,046'
                           },
                    '332': { 'city_name': 'Thessaloniki',
                             'admin_division_name': 'Central Macedonia',
                             'country_name': 'Greece',
                             'continent_name': 'Europe',
                             'population': '354,290'
                           },
                    '333': { 'city_name': 'Piraeus',
                             'admin_division_name': 'Attica',
                             'country_name': 'Greece',
                             'continent_name': 'Europe',
                             'population': '163,688'
                           },
                    '334': { 'city_name': 'Patrai',
                             'admin_division_name': 'West Greece',
                             'country_name': 'Greece',
                             'continent_name': 'Europe',
                             'population': '163,360'
                           },
                    '335': { 'city_name': 'Peristeri',
                             'admin_division_name': 'Attica',
                             'country_name': 'Greece',
                             'continent_name': 'Europe',
                             'population': '139,981'
                           },
                    '341': { 'city_name': 'Rome',
                             'admin_division_name': 'Latium',
                             'country_name': 'Italy',
                             'continent_name': 'Europe',
                             'population': '2,318,895'
                           },
                    '342': { 'city_name': 'Milan',
                             'admin_division_name': 'Lombardy',
                             'country_name': 'Italy',
                             'continent_name': 'Europe',
                             'population': '1,236,837'
                           },
                    '343': { 'city_name': 'Naples',
                             'admin_division_name': 'Campania',
                             'country_name': 'Italy',
                             'continent_name': 'Europe',
                             'population': '959,470'
                           },
                    '344': { 'city_name': 'Turin',
                             'admin_division_name': 'Piedmont',
                             'country_name': 'Italy',
                             'continent_name': 'Europe',
                             'population': '870,456'
                           },
                    '345': { 'city_name': 'Palermo',
                             'admin_division_name': 'Sicily',
                             'country_name': 'Italy',
                             'continent_name': 'Europe',
                             'population': '648,260'
                           },
                    '351': { 'city_name': 'Amsterdam',
                             'country_name': 'Netherlands',
                             'continent_name': 'Europe',
                             'admin_division_name': 'North Holland',
                             'population': '741,636'
                           },
                    '352': { 'city_name': 'Rotterdam',
                             'admin_division_name': 'South Holland',
                             'country_name': 'Netherlands',
                             'continent_name': 'Europe',
                             'population': '598,199'
                           },
                    '353': { 'city_name': 'The Hague',
                             'admin_division_name': 'South Holland',
                             'country_name': 'Netherlands',
                             'continent_name': 'Europe',
                             'population': '474,292'
                           },
                    '354': { 'city_name': 'Utrecht',
                             'admin_division_name': 'Utrecht',
                             'country_name': 'Netherlands',
                             'continent_name': 'Europe',
                             'population': '290,529'
                           },
                    '355': { 'city_name': 'Eindhoven',
                             'admin_division_name': 'North Brabant',
                             'country_name': 'Netherlands',
                             'continent_name': 'Europe',
                             'population': '209,620'
                           },
                    '361': { 'city_name': 'Madrid',
                             'admin_division_name': 'Madrid',
                             'country_name': 'Spain',
                             'continent_name': 'Europe',
                             'population': '3,255,944'
                           },
                    '362': { 'city_name': 'Barcelona',
                             'admin_division_name': 'Catalonia',
                             'country_name': 'Spain',
                             'continent_name': 'Europe',
                             'population': '1,621,537'
                           },
                    '363': { 'city_name': 'Valencia',
                             'admin_division_name': 'Valencia',
                             'country_name': 'Spain',
                             'continent_name': 'Europe',
                             'population': '814,208'
                           },
                    '364': { 'city_name': 'Seville',
                             'admin_division_name': 'Andalusia',
                             'country_name': 'Spain',
                             'continent_name': 'Europe',
                             'population': '703,206'
                           },
                    '365': { 'city_name': 'Zaragoza',
                             'admin_division_name': 'Aragon',
                             'country_name': 'Spain',
                             'continent_name': 'Europe',
                             'population': '674,317'
                           },
                    '371': { 'city_name': 'Stockholm',
                             'admin_division_name': 'Stockholm',
                             'country_name': 'Sweden',
                             'continent_name': 'Europe',
                             'population': '1,253,309'
                           },
                    '372': { 'city_name': 'Gothenburg',
                             'admin_division_name': 'Vastra Gotaland',
                             'country_name': 'Sweden',
                             'continent_name': 'Europe',
                             'population': '504,084'
                           },
                    '373': { 'city_name': 'Malmo',
                             'admin_division_name': 'Skane',
                             'country_name': 'Sweden',
                             'continent_name': 'Europe',
                             'population': '261,548'
                           },
                    '374': { 'city_name': 'Uppsala',
                             'admin_division_name': 'Uppsala',
                             'country_name': 'Sweden',
                             'continent_name': 'Europe',
                             'population': '127,734'
                           },
                    '375': { 'city_name': 'Vasteras',
                             'admin_division_name': 'Vastmanland',
                             'country_name': 'Sweden',
                             'continent_name': 'Europe',
                             'population': '107,194'
                           },
                    '411': { 'city_name': 'Kinshasa',
                             'admin_division_name': 'Kinshasa',
                             'country_name': 'Congo',
                             'continent_name': 'Africa',
                             'population': '7,785,965'
                           },
                    '412': { 'city_name': 'Lubumbashi',
                             'admin_division_name': 'Katanga',
                             'country_name': 'Congo',
                             'continent_name': 'Africa',
                             'population': '1,373,770'
                           },
                    '413': { 'city_name': 'Mbuji-Mayi',
                             'admin_division_name': 'Kasai-Oriental',
                             'country_name': 'Congo',
                             'continent_name': 'Africa',
                             'population': '874,761'
                           },
                    '414': { 'city_name': 'Kisangani',
                             'admin_division_name': 'Eastern Province',
                             'country_name': 'Congo',
                             'continent_name': 'Africa',
                             'population': '539,158'
                           },
                    '415': { 'city_name': 'Masina',
                             'admin_division_name': 'Kinshasa',
                             'country_name': 'Congo',
                             'continent_name': 'Africa',
                             'population': '485,167'
                           },
                    '421': { 'city_name': 'Cairo',
                             'admin_division_name': 'Muhafazat al Qahirah',
                             'country_name': 'Egypt',
                             'continent_name': 'Africa',
                             'population': '7,734,614'
                           },
                    '422': { 'city_name': 'Alexandria',
                             'admin_division_name': 'Alexandria',
                             'country_name': 'Egypt',
                             'continent_name': 'Africa',
                             'population': '3,811,516'
                           },
                    '423': { 'city_name': 'Giza',
                             'admin_division_name': 'Al Gizah',
                             'country_name': 'Egypt',
                             'continent_name': 'Africa',
                             'population': '2,443,203'
                           },
                    '424': { 'city_name': 'Port Said',
                             'admin_division_name': 'Muhafazat Bur Said',
                             'country_name': 'Egypt',
                             'continent_name': 'Africa',
                             'population': '538,378'
                           },
                    '425': { 'city_name': 'Suez',
                             'admin_division_name': 'As Suways',
                             'country_name': 'Egypt',
                             'continent_name': 'Africa',
                             'population': '488,125'
                           },
                    '431': { 'city_name': 'Addis Abeba',
                             'admin_division_name': 'Addis Abeba',
                             'country_name': 'Ethiopia',
                             'continent_name': 'Africa',
                             'population': '2,757,729'
                           },
                    '432': { 'city_name': 'Dire Dawa',
                             'admin_division_name': 'Dire Dawa',
                             'country_name': 'Ethiopia',
                             'continent_name': 'Africa',
                             'population': '252,279'
                           },
                    '433': { 'city_name': 'Mekele',
                             'admin_division_name': 'Tigray',
                             'country_name': 'Ethiopia',
                             'continent_name': 'Africa',
                             'population': '215,546'
                           },
                    '434': { 'city_name': 'Nazret',
                             'admin_division_name': 'Oromiya',
                             'country_name': 'Ethiopia',
                             'continent_name': 'Africa',
                             'population': '213,995'
                           },
                    '435': { 'city_name': 'Bahir Dar',
                             'admin_division_name': 'Amhara',
                             'country_name': 'Ethiopia',
                             'continent_name': 'Africa',
                             'population': '168,899'
                           },
                    '441': { 'city_name': 'Lagos',
                             'admin_division_name': 'Lagos',
                             'country_name': 'Nigeria',
                             'continent_name': 'Africa',
                             'population': '9,000,000'
                           },
                    '442': { 'city_name': 'Kano',
                             'admin_division_name': 'Kano',
                             'country_name': 'Nigeria',
                             'continent_name': 'Africa',
                             'population': '3,626,068'
                           },
                    '443': { 'city_name': 'Ibadan',
                             'admin_division_name': 'Oyo',
                             'country_name': 'Nigeria',
                             'continent_name': 'Africa',
                             'population': '3,565,108'
                           },
                    '444': { 'city_name': 'Kaduna',
                             'admin_division_name': 'Kaduna',
                             'country_name': 'Nigeria',
                             'continent_name': 'Africa',
                             'population': '1,582,102'
                           },
                    '445': { 'city_name': 'Port Harcourt',
                             'admin_division_name': 'Rivers',
                             'country_name': 'Nigeria',
                             'continent_name': 'Africa',
                             'population': '1,148,665'
                           },
                    '451': { 'city_name': 'Cape Town',
                             'admin_division_name': 'Western Cape',
                             'country_name': 'South Africa',
                             'continent_name': 'Africa',
                             'population': '3,433,441'
                           },
                    '452': { 'city_name': 'Durban',
                             'admin_division_name': 'KwaZulu-Natal',
                             'country_name': 'South Africa',
                             'continent_name': 'Africa',
                             'population': '3,120,282'
                           },
                    '453': { 'city_name': 'Johannesburg',
                             'admin_division_name': 'Gauteng',
                             'country_name': 'South Africa',
                             'continent_name': 'Africa',
                             'population': '2,026,469'
                           },
                    '454': { 'city_name': 'Soweto',
                             'admin_division_name': 'Gauteng',
                             'country_name': 'South Africa',
                             'continent_name': 'Africa',
                             'population': '1,695,047'
                           },
                    '455': { 'city_name': 'Pretoria',
                             'admin_division_name': 'Gauteng',
                             'country_name': 'South Africa',
                             'continent_name': 'Africa',
                             'population': '1,619,438'
                           },
                    '511': { 'city_name': 'Shanghai',
                             'admin_division_name': 'Shanghai Shi',
                             'country_name': 'China',
                             'continent_name': 'Asia',
                             'population': '22,315,474'
                           },
                    '512': { 'city_name': 'Beijing',
                             'admin_division_name': 'Beijing',
                             'country_name': 'China',
                             'continent_name': 'Asia',
                             'population': '11,716,620'
                           },
                    '513': { 'city_name': 'Tianjin',
                             'admin_division_name': 'Tianjin Shi',
                             'country_name': 'China',
                             'continent_name': 'Asia',
                             'population': '11,090,314'
                           },
                    '514': { 'city_name': 'Guangzhou',
                             'admin_division_name': 'Guangdong',
                             'country_name': 'China',
                             'continent_name': 'Asia',
                             'population': '11,071,424'
                           },
                    '515': { 'city_name': 'Shenzhen',
                             'admin_division_name': 'Guangdong',
                             'country_name': 'China',
                             'continent_name': 'Asia',
                             'population': '10,358,381'
                           },
                    '521': { 'city_name': 'Mumbai',
                             'admin_division_name': 'Maharashtra',
                             'country_name': 'India',
                             'continent_name': 'Asia',
                             'population': '12,691,836'
                           },
                    '522': { 'city_name': 'Delhi',
                             'admin_division_name': 'NCT',
                             'country_name': 'India',
                             'continent_name': 'Asia',
                             'population': '10,927,986'
                           },
                    '523': { 'city_name': 'Bangalore',
                             'admin_division_name': 'Karnataka',
                             'country_name': 'India',
                             'continent_name': 'Asia',
                             'population': '5,104,047'
                           },
                    '524': { 'city_name': 'Calcutta',
                             'admin_division_name': 'West Bengal',
                             'country_name': 'India',
                             'continent_name': 'Asia',
                             'population': '4,631,392'
                           },
                    '525': { 'city_name': 'Chennai',
                             'admin_division_name': 'Tamil Nadu',
                             'country_name': 'India',
                             'continent_name': 'Asia',
                             'population': '4,328,063'
                           },
                    '531': { 'city_name': 'Tokyo',
                             'admin_division_name': 'Tokyo',
                             'country_name': 'Japan',
                             'continent_name': 'Asia',
                             'population': '8,336,599'
                           },
                    '532': { 'city_name': 'Yokohama',
                             'admin_division_name': 'Kanagawa',
                             'country_name': 'Japan',
                             'continent_name': 'Asia',
                             'population': '3,574,443'
                           },
                    '533': { 'city_name': 'Osaka',
                             'admin_division_name': 'Osaka',
                             'country_name': 'Japan',
                             'continent_name': 'Asia',
                             'population': '2,592,413'
                           },
                    '534': { 'city_name': 'Nagoya',
                             'admin_division_name': 'Aichi',
                             'country_name': 'Japan',
                             'continent_name': 'Asia',
                             'population': '2,191,279'
                           },
                    '535': { 'city_name': 'Sapporo',
                             'admin_division_name': 'Hokkaido',
                             'country_name': 'Japan',
                             'continent_name': 'Asia',
                             'population': '1,883,027'
                           },
                    '541': { 'city_name': 'Kota Bharu',
                             'admin_division_name': 'Kelantan',
                             'country_name': 'Malaysia',
                             'continent_name': 'Asia',
                             'population': '1,459,994'
                           },
                    '542': { 'city_name': 'Kuala Lumpur',
                             'admin_division_name': 'Kuala Lumpur',
                             'country_name': 'Malaysia',
                             'continent_name': 'Asia',
                             'population': '1,453,975'
                           },
                    '543': { 'city_name': 'Klang',
                             'admin_division_name': 'Selangor',
                             'country_name': 'Malaysia',
                             'continent_name': 'Asia',
                             'population': '879,867'
                           },
                    '544': { 'city_name': 'Kampung Baru Subang',
                             'admin_division_name': 'Selangor',
                             'country_name': 'Malaysia',
                             'continent_name': 'Asia',
                             'population': '833,571'
                           },
                    '545': { 'city_name': 'Johor Bahru',
                             'admin_division_name': 'Johor',
                             'country_name': 'Malaysia',
                             'continent_name': 'Asia',
                             'population': '802,489'
                           },
                    '551': { 'city_name': 'Ulan Bator',
                             'admin_division_name': 'Ulaanbaatar',
                             'country_name': 'Mongolia',
                             'continent_name': 'Asia',
                             'population': '844,818'
                           },
                    '552': { 'city_name': 'Erdenet',
                             'admin_division_name': 'Orhon',
                             'country_name': 'Mongolia',
                             'continent_name': 'Asia',
                             'population': '79,647'
                           },
                    '553': { 'city_name': 'Darhan',
                             'admin_division_name': 'Darhan Uul',
                             'country_name': 'Mongolia',
                             'continent_name': 'Asia',
                             'population': '74,300'
                           },
                    '554': { 'city_name': 'Khovd',
                             'admin_division_name': 'Hovd',
                             'country_name': 'Mongolia',
                             'continent_name': 'Asia',
                             'population': '30,500'
                           },
                    '555': { 'city_name': 'Olgii',
                             'admin_division_name': 'Bayan-Olgiy',
                             'country_name': 'Mongolia',
                             'continent_name': 'Asia',
                             'population': '28,400'
                           },
                    '561': { 'city_name': 'Seoul',
                             'admin_division_name': 'Seoul',
                             'country_name': 'South Korea',
                             'continent_name': 'Asia',
                             'population': '10,349,312'
                           },
                    '562': { 'city_name': 'Busan',
                             'admin_division_name': 'Busan',
                             'country_name': 'South Korea',
                             'continent_name': 'Asia',
                             'population': '3,678,555'
                           },
                    '563': { 'city_name': 'Incheon',
                             'admin_division_name': 'Incheon',
                             'country_name': 'South Korea',
                             'continent_name': 'Asia',
                             'population': '2,628,000'
                           },
                    '564': { 'city_name': 'Daegu',
                             'admin_division_name': 'Daegu',
                             'country_name': 'South Korea',
                             'continent_name': 'Asia',
                             'population': '2,566,540'
                           },
                    '565': { 'city_name': 'Daejeon',
                             'admin_division_name': 'Daejeon',
                             'country_name': 'South Korea',
                             'continent_name': 'Asia',
                             'population': '1,475,221'
                           },
                    '611': { 'city_name': 'Sydney',
                             'admin_division_name': 'New South Wales',
                             'country_name': 'Australia',
                             'continent_name': 'Oceania',
                             'population': '4,627,345'
                           },
                    '612': { 'city_name': 'Melbourne',
                             'admin_division_name': 'Victoria',
                             'country_name': 'Australia',
                             'continent_name': 'Oceania',
                             'population': '4,246,375'
                           },
                    '613': { 'city_name': 'Brisbane',
                             'admin_division_name': 'Queensland',
                             'country_name': 'Australia',
                             'continent_name': 'Oceania',
                             'population': '2,189,878'
                           },
                    '614': { 'city_name': 'Perth',
                             'admin_division_name': 'Western Australia',
                             'country_name': 'Australia',
                             'continent_name': 'Oceania',
                             'population': '1,896,548'
                           },
                    '615': { 'city_name': 'Adelaide',
                             'admin_division_name': 'South Australia',
                             'country_name': 'Australia',
                             'continent_name': 'Oceania',
                             'population': '1,225,235'
                           },
                    '621': { 'city_name': 'Jakarta',
                             'admin_division_name': 'Jakarta Raya',
                             'country_name': 'Indonesia',
                             'continent_name': 'Oceania',
                             'population': '8,540,121'
                           },
                    '622': { 'city_name': 'Surabaya',
                             'admin_division_name': 'East Java',
                             'country_name': 'Indonesia',
                             'continent_name': 'Oceania',
                             'population': '2,374,658'
                           },
                    '623': { 'city_name': 'Medan',
                             'admin_division_name': 'North Sumatra',
                             'country_name': 'Indonesia',
                             'continent_name': 'Oceania',
                             'population': '1,750,971'
                           },
                    '624': { 'city_name': 'Bandung',
                             'admin_division_name': 'West Java',
                             'country_name': 'Indonesia',
                             'continent_name': 'Oceania',
                             'population': '1,699,719'
                           },
                    '625': { 'city_name': 'Bekasi',
                             'admin_division_name': 'West Java',
                             'country_name': 'Indonesia',
                             'continent_name': 'Oceania',
                             'population': '1,520,119'
                           },
                    '631': { 'city_name': 'Auckland',
                             'admin_division_name': 'Auckland',
                             'country_name': 'New Zealand',
                             'continent_name': 'Oceania',
                             'population': '417,910'
                           },
                    '632': { 'city_name': 'Wellington',
                             'admin_division_name': 'Wellington',
                             'country_name': 'New Zealand',
                             'continent_name': 'Oceania',
                             'population': '381,900'
                           },
                    '633': { 'city_name': 'Christchurch',
                             'admin_division_name': 'Canterbury',
                             'country_name': 'New Zealand',
                             'continent_name': 'Oceania',
                             'population': '363,926'
                           },
                    '634': { 'city_name': 'Manukau',
                             'admin_division_name': 'Auckland',
                             'country_name': 'New Zealand',
                             'continent_name': 'Oceania',
                             'population': '362,000'
                           },
                    '635': { 'city_name': 'Waitakere',
                             'admin_division_name': 'Auckland',
                             'country_name': 'New Zealand',
                             'continent_name': 'Oceania',
                             'population': '208,100'
                           },
                    '641': { 'city_name': 'City of Manila',
                             'admin_division_name': 'Metro Manila',
                             'country_name': 'Philippines',
                             'continent_name': 'Oceania',
                             'population': '10,444,527'
                           },
                    '642': { 'city_name': 'Quezon City',
                             'admin_division_name': 'Metro Manila',
                             'country_name': 'Philippines',
                             'continent_name': 'Oceania',
                             'population': '2,761,720'
                           },
                    '643': { 'city_name': 'Budta',
                             'admin_division_name': 'Muslim Mindanao',
                             'country_name': 'Philippines',
                             'continent_name': 'Oceania',
                             'population': '1,273,715'
                           },
                    '644': { 'city_name': 'Davao City',
                             'admin_division_name': 'Davao',
                             'country_name': 'Philippines',
                             'continent_name': 'Oceania',
                             'population': '1,212,504'
                           },
                    '645': { 'city_name': 'Malinao',
                             'admin_division_name': 'Soccsksargen',
                             'country_name': 'Philippines',
                             'continent_name': 'Oceania',
                             'population': '1,121,974'
                           }
                  }
  };

